In [17]:
import torch
import numpy as np
import time

device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)


cpu


In [18]:
start_time = time.time()
zeros = torch.zeros(1,1)
end_time = time.time()

elapsed_time = end_time - start_time
print(elapsed_time)

0.04277443885803223


In [2]:
randint = torch.randint(-100, 100, (6,))
randint

tensor([ -5, -96, -13,  37, -78, -97])

In [5]:
tensor = torch.tensor([[0.1 , 1.2],[2.2, 3.1],[4.9, 5.2]])
tensor

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

In [7]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [8]:
input = torch.empty(2,3)
input

tensor([[0.0000e+00, 6.4320e-43, 6.5643e-07],
        [1.0741e-05, 2.6941e+23, 3.4200e+21]])

In [9]:
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [11]:
linspace = torch.linspace(3,10, steps=5)
linspace

'''
Here's an explanation of the output:

    torch.linspace(3, 10, steps=5) generates a tensor that starts at 3 and ends at 10, with a total of 5 evenly spaced steps (values) in between.

    The first parameter, 3, is the starting point for the sequence.

    The second parameter, 10, is the ending point for the sequence.

    The steps parameter, set to 5, specifies that you want to generate 5 evenly spaced values between 3 and 10.

'''
'''
So, the output tensor contains 5 values, each spaced evenly between 3 and 10. Here are the individual values:

    The first value is 3.0000.
    The second value is 4.7500. (3.0000 + 1.7500)
    The third value is 6.5000. (3.0000 + 1.7500 + 1.7500)
    The fourth value is 8.2500. (3.0000 + 1.7500 + 1.7500 + 1.7500)
    The fifth value is 10.0000, which is the endpoint you specified.
'''

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [13]:
logspace = torch.logspace(start=10, end=10, steps=5)
logspace

'''
PyTorch's logspace function to generate a 1-D tensor containing 
values that are spaced logarithmically over a specified range

'''

tensor([1.0000e+10, 1.0000e+10, 1.0000e+10, 1.0000e+10, 1.0000e+10])

In [14]:
eye = torch.eye(5)
eye

''' 
PyTorch's eye function to create a 2D tensor that 
represents an identity matrix with a size of 5x5.

'''

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [15]:
a = torch.empty((2,3), dtype = torch.int64)
empty_like = torch.empty_like(a)
empty_like

tensor([[0, 0, 0],
        [0, 0, 0]])

In [19]:
torch_rand_1 = torch.rand(10000, 10000).to(device)
torch_rand_2 = torch.rand(10000, 10000).to(device)
np_rand_1 = torch.rand(10000, 10000)
np_rand_2 = torch.rand(10000, 10000)

start_time = time.time()
rand = (torch_rand_1 @ torch_rand_2)
end_time = time.time()

elapsed_time = end_time - start_time
print(elapsed_time)

47.01706838607788
