In [9]:
import torch
import torch.nn as nn
import numpy as np

In [4]:
sample = torch.tensor([10.,10.,10.])
linear = nn.Linear(3,3, bias=False)
print(linear(sample))

'''
A linear transformation, in the context of neural networks and linear algebra, 
is a mathematical operation that takes an input vector (or tensor) and produces 
an output vector through a linear mapping

the specific linear transformation is represented by the nn.Linear(3, 3, bias=False) line, where:

    3 represents the dimensionality of the input vector.
    3 represents the dimensionality of the output vector.
    bias=False indicates that there are no bias terms associated with this linear transformation.


Mathematically, a linear transformation can be represented as follows:
y = Wx
Where:
    y is the output vector.
    x is the input vector.
    W is the weight matrix, which defines how the input is transformed to produce the output.

the nn.Linear module initializes this weight matrix W based on the specified input and output dimensions. 
When you apply this linear transformation to the sample tensor with linear(sample), it calculates the 
dot product between the input vector sample and the weight matrix W, producing a 3-dimensional output vector.
'''

tensor([12.6325, -4.2024, -2.0181], grad_fn=<SqueezeBackward3>)


'\nA linear transformation, in the context of neural networks and linear algebra, \nis a mathematical operation that takes an input vector (or tensor) and produces \nan output vector through a linear mapping\n\nthe specific linear transformation is represented by the nn.Linear(3, 3, bias=False) line, where:\n\n    3 represents the dimensionality of the input vector.\n    3 represents the dimensionality of the output vector.\n    bias=False indicates that there are no bias terms associated with this linear transformation.\n\n\nMathematically, a linear transformation can be represented as follows:\ny = Wx\nWhere:\n    y is the output vector.\n    x is the input vector.\n    W is the weight matrix, which defines how the input is transformed to produce the output.\n\nthe nn.Linear module initializes this weight matrix W based on the specified input and output dimensions. \nWhen you apply this linear transformation to the sample tensor with linear(sample), it calculates the \ndot product be

In [5]:
import torch.nn.functional as F

tensor_1 = torch.tensor([1.0, 2.0,3.0])
softmax_out = F.softmax(tensor_1, dim=0)

print(softmax_out)

''' 
The softmax function first exponentiates each element of the input tensor. 
In our case, we calculate e^1.0, e^2.0, and e^3.0.

These exponentiated values are then normalized. 
This involves dividing each exponentiated value by the sum of all the exponentiated values.

softmax_out[0] = e^1.0 / (e^1.0 + e^2.0 + e^3.0)
softmax_out[1] = e^2.0 / (e^1.0 + e^2.0 + e^3.0)
softmax_out[2] = e^3.0 / (e^1.0 + e^2.0 + e^3.0)


'''

tensor([0.0900, 0.2447, 0.6652])


In [6]:
# Embedding example

vocab_size = 1000
embedding_dim = 100
embedding = nn.Embedding(vocab_size, embedding_dim)

input_indices = torch.LongTensor([1,5,3,2])

embedded_output = embedding(input_indices)



In [8]:
embedded_output[0]

tensor([-0.7141,  0.0562, -0.2028, -0.7535, -2.0878,  1.8895,  0.4802, -1.3629,
        -0.6780, -0.5944,  0.0061, -2.4262, -0.1263, -1.6117,  0.0049, -1.7066,
         0.2956,  0.4144,  0.5867,  0.7812,  0.2897, -0.4531,  2.2317, -0.6937,
        -0.3222,  0.3711,  0.6082, -0.4153,  1.2835, -1.6107,  0.9861,  1.2927,
        -1.3491, -0.1391, -0.7601,  1.1158, -0.2805, -1.2785, -0.6942, -1.3419,
        -0.6739,  1.1143, -2.4807, -0.4945, -1.5342, -0.2980, -1.6055,  0.7699,
         0.4636, -0.0799, -0.2189,  0.0073,  0.8336, -0.8915, -1.7746, -0.5397,
        -0.5808,  0.0962,  1.9988, -0.8394,  1.6788, -1.0648,  0.0757, -0.8841,
         0.2622, -0.9124, -1.0700, -0.0353,  0.1188,  0.8628, -0.4179, -0.9719,
         0.8884,  1.1437, -0.1747, -0.7622,  0.2384, -0.5126,  0.6451, -0.3315,
        -0.8950,  0.7832,  0.4548, -0.0414, -0.9836,  0.3304,  0.7972, -1.6520,
         0.3203, -0.3643,  1.6726, -1.0870,  0.4368, -0.3060,  0.4171, -0.8036,
         1.1157, -0.8875,  0.3075,  0.76

In [15]:
# Dot products and matmuls

a = np.array([[1,2],[3,4],[5,6]])
b = np.array([[2,8,4],[10,11,12]])

a_tensor = torch.Tensor(a)
b_tensor = torch.Tensor(b)

print(a_tensor.shape)
print(b_tensor.shape)

print('result', a_tensor @ b_tensor)

torch.Size([3, 2])
torch.Size([2, 3])
result tensor([[ 22.,  30.,  28.],
        [ 46.,  68.,  60.],
        [ 70., 106.,  92.]])


In [17]:
# Logits and view

a = torch.rand(2,3,5)
x, y , z = a.shape

a = a.view(x,y,z)
print(a.shape)

torch.Size([2, 3, 5])
